# Generated by Django 4.2.11 on 2025-11-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0006_add_user_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='long_term_summary',
            field=models.TextField(blank=True, help_text='Długoterminowe wnioski AI dotyczące terapii pacjenta.', null=True),
        ),
    ]
