# Generated by Django 4.2.11 on 2025-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0007_session_long_term_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='long_term_summary',
        ),
        migrations.AddField(
            model_name='patient',
            name='long_term_summary',
            field=models.TextField(blank=True, help_text='Długoterminowa analiza AI dotycząca postępów pacjenta w terapii.', null=True),
        ),
    ]
